import IISStomatologichskaya_klinikaЗаписьEController from '../i-i-s-stomatologichskaya-klinika-запись-e';

var IISStomatologichskaya_klinikaЗаписьENewController = IISStomatologichskaya_klinikaЗаписьEController;
export default IISStomatologichskaya_klinikaЗаписьENewController;
