import IISStomatologichskaya_klinikaКабинетEController from '../i-i-s-stomatologichskaya-klinika-кабинет-e';

var IISStomatologichskaya_klinikaКабинетENewController = IISStomatologichskaya_klinikaКабинетEController;
export default IISStomatologichskaya_klinikaКабинетENewController;
